# Generated by Django 4.2.18 on 2025-01-23 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_driver_slug_trip_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='end_point',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='trip',
            name='start_point',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='trip',
            name='car_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_as_car', to='mainapp.car'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_as_driver', to='mainapp.driver'),
        ),
    ]
